version: '3.8'
services:
  api:
    build: ./backend
    container_name: api_backend
    ports:
      - '3001:3001'
    environment:
      - API_KEY=b9630d3d0674aca0e246295c
  client:
    build: ./frontend
    container_name: client_frontend
    ports:
      - '3000:3000'
    environment:
      - API_ENDPOINT=api_backend
    stdin_open: true
    tty: true