version: "3"
services:
  api:
    build: ./backend
    container_name: api_backend
    ports:
      - 3001:3001
    environment:
      - API_KEY=${API_KEY}
      - PORT=3001
  client:
    build: ./frontend
    container_name: client_frontend
    ports:
      - 3000:80
    environment:
      - API_ENDPOINT=api
    links:
      - api